config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :orders
  resources :employees
  resources :positions
  resources :deliveries
  resources :clients
  resources :preparats
  resources :providers
  resources :types
  resources :manufacturers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #Главная страница будет загружаться первой
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord

#Валидация
validates :name, :adress, :phone, presence: true

#Сущность "Клиент"
#связана с сущностью "Заказы" связью один ко многим
#один "Клиент" может делать много заказов
has_many :orders

end

app/models/delivery.rb
class Delivery < ApplicationRecord

#Валидация
validates :name, :phone, presence: true

#Сущность "Доставка"
#связана с сущностью "Заказы" связью один ко многим
#одина "Доставка" может использоваться много раз в заказах
has_many :orders

end

app/models/employee.rb
class Employee < ApplicationRecord

#Валидация
validates :family, :adress, :phone, :description, :position_id, presence: true

#Сущность "Сотрудник"
#связана с сущностью "Заказы" связью один ко многим
#один "Сотрудник" может оформлять много заказов
has_many :orders


#Сущность "Сотрудник"
#связана с сущностью (таблицей справочником) "Должность сотрудника"
belongs_to :position

end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord

#Валидация
validates :name, :adress, :phone, :email, presence: true

#Сущность "Изготовите"
#связана с сущностью "Препараты" связью один ко многим
#один "Изготовитель" может изготавливать множество препаратов
has_many :preparats

end

app/models/order.rb
class Order < ApplicationRecord

#Валидация
validates :datepublic, :dateperformance, :costdelivery, :client_id, :delivery_id, :employee_id, presence: true

#Сущность "Заказы"
#связана с сущностями (таблицами справочниками) "Клиент", "Доставка", "Сотрудник"
belongs_to :client
belongs_to :delivery
belongs_to :employee

#Таблица заказы связана с таблицей "Препараты" связьм многие-ко-многим
#через таблицу "Заказано"
has_many :ordereds, :dependent => :destroy # уничтожать вместе с основным экземпляром
has_many :preparats, through: :ordereds

accepts_nested_attributes_for :ordereds, :allow_destroy => true

end

app/models/ordered.rb
class Ordered < ApplicationRecord

#Валидация
validates :preparat_id, presence: true

#Данная таблица осуществляет связь многие-ко-многим
#между таблицами "Препараты" и "Заказы"
belongs_to :preparat
belongs_to :order

end

app/models/position.rb
class Position < ApplicationRecord

#Валидация
validates :name, presence: true


#Сущность "Должность сотрудника"
#связана с сущностью "Сотрудник" связью один ко многим
#одина "Должность" может относиться ко многим сотрудникам
has_many :employees

end

app/models/preparat.rb
class Preparat < ApplicationRecord

#Валидация
validates :name, :cost, :dateofmanufacturer, :shelflife, :manufacturer_id, :type_id, :provider_id, presence: true

#Сущность "Препараты"
#связана с сущностями (таблицами справочниками) "Изготовитель", "Тип", "Поставщик"
belongs_to :manufacturer
belongs_to :type
belongs_to :provider

#Таблица препараты связана с таблицей "Заказы" связьм многие-ко-многим
#через таблицу "Заказано"
has_many :ordereds, :dependent => :destroy # уничтожать вместе с основным экземпляром
has_many :orders, through: :ordereds

end

app/models/provider.rb
class Provider < ApplicationRecord

#Валидация
validates :name, :adress, :phone, :email, presence: true

#Сущность "Поставщик"
#связана с сущностью "Препараты" связью один ко многим
#один "Поставщик" может поставлять множество препаратов
has_many :preparats

end

app/models/type.rb
class Type < ApplicationRecord

#Валидация
validates :typeform, presence: true

#Сущность "Тип"
#связана с сущностью "Препараты" связью один ко многим
#один "Тип" может может относиться к многим препаратам
has_many :preparats

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
    #Для подстановки нужны следующие переменные
    @positions=Position.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Новый сотрудник был успешно добавлен.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Информация о сотруднике была успешно обновлена.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Информация о сотруднике была успешно удалена.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
      #Также нужны переменные
      @position=Position.find(@employee.position_id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:family, :name, :adress, :phone, :description, :position_id)
    end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: [:show, :edit, :update, :destroy]

  # GET /types
  # GET /types.json
  def index
    @types = Type.all
  end

  # GET /types/1
  # GET /types/1.json
  def show
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types
  # POST /types.json
  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: 'Новый тип лекарственной формы был успешно добавлен.' }
        format.json { render :show, status: :created, location: @type }
      else
        format.html { render :new }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /types/1
  # PATCH/PUT /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to @type, notice: 'Информация о типе лекарственной формы была успешно обновлена.' }
        format.json { render :show, status: :ok, location: @type }
      else
        format.html { render :edit }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type.destroy
    respond_to do |format|
      format.html { redirect_to types_url, notice: 'Информация о типе лекарственной формы была успешно удалена.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_params
      params.require(:type).permit(:typeform)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/deliveries_helper.rb
module DeliveriesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper

def title
 
@order.ordereds.build
end
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/preparats_helper.rb
module PreparatsHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/employees/_form.html.erb
<%= form_for(employee) do |f| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<table width="100%">
  <tr>
     <td id="MyLeft">
        Фамилия, Имя и Отчество:
     </td>
     <td id="MyRight">
        <%= f.text_field :family, :size=>"40", :maxlength=>"40" %>
     </td>
  </tr>
  <tr>
     <td id="MyLeft">
        Адрес:
     </td>
     <td id="MyRight">
        <%= f.text_field :adress, :size=>"50", :maxlength=>"50" %>
     </td>
  </tr>
  <tr>
     <td id="MyLeft">
        Телефон:
     </td>
     <td id="MyRight">
        <%= f.text_field :phone, :size=>"15", :maxlength=>"15" %>
     </td>
  </tr>
  <tr>
     <td id="MyLeft">
        Описание:
     </td>
     <td id="MyRight">
        <%= f.text_area :description, :size=>"80x7", :maxlength=>"560" %>
     </td>
  </tr>
  <tr>
     <td id="MyLeft">
        Выберите должность:
     </td>
     <td id="MyRight">
        <%= f.collection_select(:position_id, Position.all, :id, :name) %>
     </td>
  </tr>
</table>
  <br />
  <div class="actions">
    <%= f.submit ( f.object.new_record? ? "Создать" : "Обновить"), class: "btn" %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Редактирование</h1>
<hr>
<%= render 'form', employee: @employee %>
<h4>
<%= link_to 'Подробнее', @employee %> |
<%= link_to 'Назад', employees_path %></h4>
<br /><hr>
<h3><div id="MyFooter">Copyright by Вавилов А. А. группа: М15-ИСТ-3</div></h3>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Справочние "Сотрудников"</h1>
<hr>
<table>
  <thead>
    <tr>
      <th>Фамилия, Имя и Отчество</th>
      <th>Адресс</th>
      <th>Телефон</th>
      <th>Описание</th>
      <th>Должность</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.family %></td>
        <td><%= employee.adress %></td>
        <td><%= employee.phone %></td>
        <td><%= employee.description %></td>
        <td>
          <% @positions.each do |position| %>
            <% if position.id == employee.position_id %>
               <%= position.name %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Показать', employee %></td>
        <td><%= link_to 'Редактировать', edit_employee_path(employee) %></td>
        <td><%= link_to 'Удалить', employee, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<h4>
<%= link_to 'Добавить нового сотрудника', new_employee_path %><br /><br />
<%= link_to "Выйти на главное меню", :controller => "welcome" %></h4>
<br /><hr>
<h3><div id="MyFooter">Copyright by Вавилов А. А. группа: М15-ИСТ-3</div></h3>

app/views/employees/new.html.erb
<h1>Добавление нового сотрудника</h1>
<hr>
<%= render 'form', employee: @employee %>
<h4>
<%= link_to 'Назад', employees_path %></h4>
<br /><hr>
<h3><div id="MyFooter">Copyright by Вавилов А. А. группа: М15-ИСТ-3</div></h3>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Справочние "Сотрудников"</h1>
<hr>
<p>
  <strong>Фамилия, Имя и Отчество:</strong>
  <%= @employee.family %>
</p>

<p>
  <strong>Адресс:</strong>
  <%= @employee.adress %>
</p>

<p>
  <strong>Телефон:</strong>
  <%= @employee.phone %>
</p>

<p>
  <strong>Описание:</strong>
  <%= @employee.description %>
</p>

<p>
  <strong>Должность:</strong>
  <%= @position.name %>
</p>
<h4>
<%= link_to 'Редактировать', edit_employee_path(@employee) %> |
<%= link_to 'Назад', employees_path %></h4>
<br /><hr>
<h3><div id="MyFooter">Copyright by Вавилов А. А. группа: М15-ИСТ-3</div></h3>