config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :orders
  resources :employees
  resources :positions
  resources :deliveries
  resources :clients
  resources :preparats
  resources :providers
  resources :types
  resources :manufacturers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #Главная страница будет загружаться первой
  root 'welcome#index'
end

app/models/preparat.rb
class Preparat < ApplicationRecord

#Валидация
validates :name, :cost, :dateofmanufacturer, :shelflife, :manufacturer_id, :type_id, :provider_id, presence: true

#Сущность "Препараты"
#связана с сущностями (таблицами справочниками) "Изготовитель", "Тип", "Поставщик"
belongs_to :manufacturer
belongs_to :type
belongs_to :provider

#Таблица препараты связана с таблицей "Заказы" связьм многие-ко-многим
#через таблицу "Заказано"
has_many :ordereds, :dependent => :destroy # уничтожать вместе с основным экземпляром
has_many :orders, through: :ordereds

end

app/controllers/preparats_controller.rb
class PreparatsController < ApplicationController
  before_action :set_preparat, only: [:show, :edit, :update, :destroy]

  # GET /preparats
  # GET /preparats.json
  def index
    @preparats = Preparat.all
    #Для подстановки нужны следующие переменные
    @manufacturers=Manufacturer.all
    @types=Type.all
    @providers=Provider.all
  end

  # GET /preparats/1
  # GET /preparats/1.json
  def show
  end

  # GET /preparats/new
  def new
    @preparat = Preparat.new
  end

  # GET /preparats/1/edit
  def edit
  end

  # POST /preparats
  # POST /preparats.json
  def create
    @preparat = Preparat.new(preparat_params)

    respond_to do |format|
      if @preparat.save
        format.html { redirect_to @preparat, notice: 'Новый препарат успешно добавлен.' }
        format.json { render :show, status: :created, location: @preparat }
      else
        format.html { render :new }
        format.json { render json: @preparat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /preparats/1
  # PATCH/PUT /preparats/1.json
  def update
    respond_to do |format|
      if @preparat.update(preparat_params)
        format.html { redirect_to @preparat, notice: 'Информация о препарате была успешно обновлена.' }
        format.json { render :show, status: :ok, location: @preparat }
      else
        format.html { render :edit }
        format.json { render json: @preparat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /preparats/1
  # DELETE /preparats/1.json
  def destroy
    @preparat.destroy
    respond_to do |format|
      format.html { redirect_to preparats_url, notice: 'Информация о препарате была успешно удалена.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_preparat
      @preparat = Preparat.find(params[:id])
      #Также нужны переменные
      @manufacturer=Manufacturer.find(@preparat.manufacturer_id)
      @type=Type.find(@preparat.type_id)
      @provider=Provider.find(@preparat.provider_id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def preparat_params
      params.require(:preparat).permit(:name, :cost, :dateofmanufacturer, :shelflife, :description, :manufacturer_id, :type_id, :provider_id)
    end
end

app/helpers/preparats_helper.rb
module PreparatsHelper
end

app/views/preparats/_form.html.erb
<%= form_for(preparat) do |f| %>
  <% if preparat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(preparat.errors.count, "error") %> prohibited this preparat from being saved:</h2>

      <ul>
      <% preparat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<table width="100%">
  <tr>
    <td id="MyLeft">
       Название:
    </td>
    <td id="MyRight">
       <%= f.text_field :name, :size=>"20", :maxlength=>"20" %>
    </td>
  </tr>
  <tr>
    <td id="MyLeft">
       Стоимость:
    </td>
    <td id="MyRight">
       <%= f.text_field :cost, :size=>"10", :maxlength=>"10" %> руб.
    </td>
  </tr>
  <tr>
    <td id="MyLeft">
       Дата изготовления:
    </td>
    <td id="MyRight">
       <%= f.date_select :dateofmanufacturer %>
    </td>
  </tr>
  <tr>
    <td id="MyLeft">
       Срок годности:
    </td>
    <td id="MyRight">
       <%= f.number_field :shelflife, :size=>"5", :maxlength=>"5" %>лет.
    </td>
  </tr>
  <tr>
    <td id="MyLeft">
       Описание:
    </td>
    <td id="MyRight">
       <%= f.text_area :description, :size=>"80x5", :maxlength=>"400" %>
    </td>
  </tr>
  <tr>
    <td id="MyLeft">
      Выберите изготовителя:
    </td>
    <td id="MyRight">
       <%= f.collection_select(:manufacturer_id, Manufacturer.all, :id, :name) %>
    </td>
  </tr>
  <tr>
    <td id="MyLeft">
        Выберите тип:
    </td>
    <td id="MyRight">
       <%= f.collection_select(:type_id, Type.all, :id, :typeform) %>
    </td>
  </tr>
  <tr>
    <td id="MyLeft">
       Выберите поставщика:
    </td>
    <td id="MyRight">
       <%= f.collection_select(:provider_id, Provider.all, :id, :name) %>
    </td>
  </tr>
</table>
  <br />
  <div class="actions">
    <%= f.submit ( f.object.new_record? ? "Создать" : "Обновить"), class: "btn" %>
  </div>
<% end %>

app/views/preparats/edit.html.erb
<h1>Редактирование</h1>
<hr>
<%= render 'form', preparat: @preparat %>
<h4>
<%= link_to 'Подробнее', @preparat %> |
<%= link_to 'Назад', preparats_path %></h4>
<br /><hr>
<h3><div id="MyFooter">Copyright by Вавилов А. А. группа: М15-ИСТ-3</div></h3>

app/views/preparats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Препараты</h1>
<hr>
<table>
  <thead>
    <tr>
      <th>Название</th>
      <th>Стоимость (руб.)</th>
      <th>Дата изготовления</th>
      <th>Срок годности (лет)</th>
      <th>Описание</th>
      <th>Изготовитель</th>
      <th>Тип</th>
      <th>Поставщик</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @preparats.each do |preparat| %>
      <tr>
        <td><%= preparat.name %></td>
        <td><%= preparat.cost %></td>
        <td><%= preparat.dateofmanufacturer %></td>
        <td><%= preparat.shelflife %></td>
        <td><%= preparat.description %></td>
        <td>
          <% @manufacturers.each do |manufacturer| %>
            <% if manufacturer.id == preparat.manufacturer_id %>
               <%= manufacturer.name %>
            <% end %>
          <% end %>
        </td>
        <td>
            <% @types.each do |type| %>
            <% if type.id == preparat.type_id %>
               <%= type.typeform %>
            <% end %>
            <% end %>
        </td>
        <td>
            <% @providers.each do |provider| %>
            <% if provider.id == preparat.provider_id %>
               <%= provider.name %>
            <% end %>
            <% end %>
        </td>
        <td><%= link_to 'Показать', preparat %></td>
        <td><%= link_to 'Редактировать', edit_preparat_path(preparat) %></td>
        <td><%= link_to 'Удалить', preparat, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<h4>
<%= link_to 'Добавить новый препарат', new_preparat_path %><br /><br />
<%= link_to "Выйти на главное меню", :controller => "welcome" %></h4>
<br /><hr>
<h3><div id="MyFooter">Copyright by Вавилов А. А. группа: М15-ИСТ-3</div></h3>

app/views/preparats/new.html.erb
<h1>Добавление нового препарата</h1>
<hr>
<%= render 'form', preparat: @preparat %>
<h4>
<%= link_to 'Назад', preparats_path %></h4>
<br /><hr>
<h3><div id="MyFooter">Copyright by Вавилов А. А. группа: М15-ИСТ-3</div></h3>

app/views/preparats/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Препараты</h1>
<hr>
<p>
  <strong>Название:</strong>
  <%= @preparat.name %>
</p>

<p>
  <strong>Стоимость:</strong>
  <%= @preparat.cost %> руб.
</p>

<p>
  <strong>Дата изготовления:</strong>
  <%= @preparat.dateofmanufacturer %>
</p>

<p>
  <strong>Срок годности:</strong>
  <%= @preparat.shelflife %> лет.
</p>

<p>
  <strong>Описание:</strong>
  <%= @preparat.description %>
</p>

<p>
  <strong>Изготовитель:</strong>
  <%= @manufacturer.name %>
</p>

<p>
  <strong>Тип:</strong>
  <%= @type.typeform %>
</p>

<p>
  <strong>Поставщик:</strong>
  <%= @provider.name %>
</p>
<h4>
<%= link_to 'Редактировать', edit_preparat_path(@preparat) %> |
<%= link_to 'Назад', preparats_path %></h4>
<br /><hr>
<h3><div id="MyFooter">Copyright by Вавилов А. А. группа: М15-ИСТ-3</div></h3>